### ISSUE TITLE
Algorithm?

### ISSUE THREAD

**Issue by Kaos-Industries** [Joyez/renault-radio-code-list#1]
Hey there.

Firstly, brilliant find, and one that's much appreciated. I can only imagine how you got hold of this. I'm wondering if the radio codes have an algorithm in common, something that converts the precode into the radio code? Or are the two entirely unrelated, with each precode mapped individually to a random code?

**Comment by nitrxgen** [comment]
Hi,
I noticed nobody answered your question yet. The codes produced are a result of some basic arithmetics applied to the challenge (or "precode"). The prefixed letter is treated as a number from 0 ("A") to 25 ("Z") and the following digits help mangle it up with some basic operations and the final number uses modulo to keep it under 5 digits. All in all, it's literally like 3 lines of human readable code. There's no mapping involved. I may think about releasing a source code in the future; these radio codes are super easy to obtain it really doesn't prevent radio unit thefts in my opinion, any thief would find it easy to unlock. These codes are more of a burden to innocent car owners more than anything.
Regards,

**Comment by yhondri** [comment]
Hi @nitrxgen , ¿Did you release the algorithm? I'm a little curious about it. 
Which are the operations to decode the precode?

Regards.

**Comment by kpym** [comment]
Check https://github.com/kpym/autoradio-renault

**Comment by hanynigma** [comment]
> Check https://github.com/kpym/autoradio-renault

very helpful Thanks for Share

I want algo for ford serials Starts with V 
can you help ?
